peer_key: "CAESQBa/lNg0/GHhzjf03oYvHfDYf9VnkQImE9lPB8Zrf4JICBKHPB5PbIzQoCkWwBrkha4xgpIerre4B5zZ5J7f/W8="
proxy:
  addr: 0.0.0.0:1082
  server_peer: "/ip4/64.176.227.5/tcp/11212/ws/p2p/12D3KooWJJqoWuC2CVAuUfEfdLHguh1bPbKsLwQY4SoC2Vw695ry"