peer_key: "CAESQKheHgpBqkqq5pxNg+0hxjtRdL99q/uOcDxUoAWhs1DWh/O+p8NH1yCEP7Ri+rdbpbHS7vnBBD8zxY2320F2d8U="
ssh_server: 127.0.0.1:22
network:
  enable_nat: true
  listen_addrs:
    - "/ip4/0.0.0.0/udp/11211/quic"
    - "/ip6/::/udp/11211/quic"
    - "/ip4/0.0.0.0/tcp/11211"
    - "/ip6/::/tcp/11211"
    - "/ip4/0.0.0.0/tcp/11212/ws"
    - "/ip6/::/tcp/11212/ws"
  relays:
    - "/ip4/64.176.227.5/tcp/4001/p2p/12D3KooWLzi9E1oaHLhWrgTPnPa3aUjNkM8vvC8nYZp1gk9RjTV1"
acl:
  allow_peers: []
  allow_subnets: []